name: Run Markdown Linting

on:
  workflow_call:

jobs:
  md_lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
      with:
        python-version-file: .python-version
    - name: Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7
    - name: Install linting requirements
      run: uv sync --locked --group codespell
    - name: Run codespell check
      run: uv run codespell
