name: Run Ruff Linting and Formatting

on:
  workflow_call:

jobs:
  python_lint:
    name: Python Linting and Formatting checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
      with:
        python-version-file: .python-version
    - name: Install uv
      uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7
    - name: Install linting requirements
      run: uv sync --locked --group linting
    - name: Run Python linting check
      run: uv run ruff check --no-fix --output-format github
    - name: Run Python formatting check
      run: uv run ruff format --diff
