name: Run Static Type Checks

on:
  workflow_call:

jobs:
  mypy_check:
    name: Type Checking
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6
    - name: Install type checking requirements
      run: uv sync --locked --group typing --all-extras
    - name: Run Static Type Checks
      run: uv run mypy --no-incremental --python-version ${{ matrix.python-version }}
